# Site settings
title: _owenschebella.com
email: oschebell@gmail.com
description: My simple developer blog.
baseurl: "/developer-blog"
twitter_username: oschebell
avatar: "https://pbs.twimg.com/profile_images/620818628481384448/a0oa69Gj.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Owen Schebella" # Set default author name
      categories: "web"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
